import type { Metadata } from "next";
import { Roboto, Scada, Onest } from "next/font/google";
import "./globals.scss";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});
const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});
const scada = Scada({
  weight: ["400", "700"],
  subsets: ["latin", "cyrillic"],
  variable: "--font-scada",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${scada.variable} ${onest.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
